[workspace]
resolver = "2"
members = ["wgpu", "fragments-core", "fragments-glfw", "fragments-examples"]

[workspace.dependencies]
glam = "0.22"
flax = { git = "https://github.com/ten3roberts/flax", version = "*" }
