[workspace]
resolver = "2"
members = [
    "fragments-wgpu",
    "fragments-core",
    "fragments-glfw",
    "fragments-examples",
    "examples/*",
]

[workspace.dependencies]
glam = "0.23"
flax = { git = "https://github.com/ten3roberts/flax", version = "*" }
anyhow = "1.0"
tracing = "0.1"
